-- Auto-generated from schema-map-postgres.psd1 (map@9d3471b)
-- engine: postgres
-- table:  key_events
CREATE TABLE IF NOT EXISTS key_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_id BIGINT NULL,
  basename VARCHAR(100) NULL,
  event_type TEXT NOT NULL,
  actor_id BIGINT NULL,
  job_id BIGINT NULL,
  note TEXT NULL,
  meta JSONB NULL,
  "source" TEXT NOT NULL DEFAULT 'admin',
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_key_events_type CHECK (event_type IN ('created','rotated','activated','retired','compromised','deleted','used_encrypt','used_decrypt','access_failed','backup','restore')),
  CONSTRAINT chk_key_events_source CHECK ("source" IN ('cron','admin','api','manual'))
);
